### ISSUE TITLE
Timer not right

### ISSUE THREAD

**Issue by blakenorthrup** [mykle1/MMM-EventHorizon#1]
Hi, I have a countdown timer set for an event at 7:30pm or 19:30, and it is showing 02:35:18 at the current time of 3:54pm. I am in CST, and the clock on my RaspberryPi, and MagicMirror are both correct. Timer is an hour off.

**Comment by mykle1** [comment]
I just tested the module with a 19:30 event (it can't be 7:30 for pm) and the module performs as expected accurately. I'm sorry you're have trouble with it. If you wouldn't mind creating a topic on the MM forum I can better help you there. I'd like to have a  look at your config entry which is better viewed there than here

**Comment by mykle1** [comment]
Updated the module if you are interested

**Comment by blakenorthrup** [comment]
Yes, very interested. Thanks!

**Comment by blakenorthrup** [comment]
Works like a champ mkyle1! Great work man!
