### ISSUE TITLE
Changing color

### ISSUE THREAD

**Issue by blakenorthrup** [mykle1/MMM-EventHorizon#2]
Hi, sorry if this is a dumb question, but I seem to be having trouble changing the color of my event. I added everything to the custom.css file, located in /home/pi/magicmirror/css, but nothing happens. Can you help?

**Comment by mykle1** [comment]
You can't accomplish that will css as the module is in an iFrame. However, if you wish, you can go to this website https://www.timeanddate.com/clocks/freecountdown.html and create your own, including size, color, etc.. Near the bottom of that page is a button called "Show HTML for Countdown timer". You click that after you design your timer. You will be presented with an iframe source url. That url can be edited into the module, with some modifications. Good luck!

**Comment by blakenorthrup** [comment]
Thank you mkyle1. Love the module!

**Comment by spitzlbergerj** [comment]
Hi,
I also changed the text color by editing the MMM EventHorizon.js. Specifically, I replaced all occurrences of "0ff" with "fff" to get a white font. However, I always have to follow this change when updating.
Would it be possible for you to insert a parameter that sets the general color?
Thank you very much already! ;-)

**Comment by blakenorthrup** [comment]
Hey mkyle, thanks for the follow up. I will test this as soon as I get back home. 

On January 12, 2019 4:02:50 AM CST, spitzlbergerj <notifications@github.com> wrote:
>Hi,
>I also changed the text color by editing the MMM EventHorizon.js.
>Specifically, I replaced all occurrences of "0ff" with "fff" to get a
>white font. However, I always have to follow this change when updating.
>Would it be possible for you to insert a parameter that sets the
>general color?
>Thank you very much already! ;-)
>
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/mykle1/MMM-EventHorizon/issues/2#issuecomment-453735137

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
