### ISSUE TITLE
[Feature] Adding customized countdown timer

### ISSUE THREAD

**Issue by moryoav** [mykle1/MMM-EventHorizon#4]
I was looking for a way to add a 2 minute countdown timer, instead of a fixed time that's hard-coded in the .js file.
My suggestion:
```
notificationReceived: function(notification, payload) {
        if (notification === 'HIDE_TIMER') {
            this.hide(1000);
        } else if (notification === 'SHOW_TIMER') {
            this.show(1000);
        } else if (notification === 'START_TIMER') {
            var today = new Date();
            var dd = String(today.getDate()).padStart(2, '0');
            var mm = String(today.getMonth() + 1).padStart(2, '0');
            var yyyy = today.getFullYear();
            this.config.date = yyyy + '-' + mm + '-' + dd;

            var now = today.getTime()+2*60000;
            var hours = String(Math.floor((now / (1000 * 60 * 60)) % 24)).padStart(2, '0');
            var minutes = String(Math.floor((now / (1000 * 60)) % 60)).padStart(2, '0');
            var seconds = String(Math.floor((now / 1000) % 60)).padStart(2, '0');
            this.config.time = hours + ':' + minutes + ':' + seconds;
            this.show(1000);
            this.updateDom();
        }
    },

```
I thought I'd activate it using MMM-Remote-Control's API function.
I wasn't able to use the API function, but this seems to work just fine:
`http://localhost:8080/remote?action=NOTIFICATION&notification=START_TIMER`

Any thoughts?

**Comment by mykle1** [comment]
Feel free to fork the repo and make any changes you like. I think if it was me, I would fork the repo and strip it down to create an entire new module out of it, for example, MMM-TwoMinuteTimer, but that's just me. I'm going to close this issue as it's a feature request and not necessarily an issue. Thanks for your interest in the module and have fun with it. Peace.
